/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => EntropyInboxProcessor
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var import_util = require("util");
var path = __toESM(require("path"));
var execAsync = (0, import_util.promisify)(import_child_process.exec);
var VIEW_TYPE_INBOX = "entropy-inbox-processor";
var DEFAULT_SETTINGS = {
  aiEnabled: false,
  aiProvider: "anthropic",
  apiKey: "",
  model: "",
  pythonPath: "python3",
  autoArchive: true,
  confirmBeforeApply: true
};
var EntropyInboxProcessor = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.statusBarItem = this.addStatusBarItem();
    this.updateStatusBar();
    this.registerView(
      VIEW_TYPE_INBOX,
      (leaf) => new InboxProcessorView(leaf, this)
    );
    this.addRibbonIcon("inbox", "Entropy: Process Inbox", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-inbox-processor",
      name: "Open Inbox Processor",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "analyze-inbox",
      name: "Analyze Inbox Now",
      callback: async () => {
        var _a;
        await this.activateView();
        const view = (_a = this.app.workspace.getLeavesOfType(VIEW_TYPE_INBOX)[0]) == null ? void 0 : _a.view;
        if (view) {
          await view.analyze();
        }
      }
    });
    this.addSettingTab(new EntropySettingTab(this.app, this));
    this.registerInterval(
      window.setInterval(() => this.updateStatusBar(), 6e4)
      // Every minute
    );
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_INBOX);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE_INBOX, active: true });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async updateStatusBar() {
    try {
      const count = await this.getInboxCount();
      this.statusBarItem.setText(`\u{1F4E5} ${count}`);
      this.statusBarItem.setAttribute("aria-label", `${count} items in inbox`);
    } catch (error) {
      this.statusBarItem.setText("\u{1F4E5} ?");
    }
  }
  async getInboxCount() {
    const inboxFolders = ["00-Inbox", "Clippings", "raw"];
    let count = 0;
    for (const folder of inboxFolders) {
      const folderPath = `${folder}/`;
      const files = this.app.vault.getMarkdownFiles().filter(
        (f) => f.path.startsWith(folderPath) && !f.path.includes("/processed/")
      );
      count += files.length;
    }
    return count;
  }
  async runPythonScript(scriptName, args = []) {
    const vaultPath = this.app.vault.adapter.basePath;
    const scriptPath = path.join(vaultPath, ".agent/skills/process-inbox", scriptName);
    const command = `${this.settings.pythonPath} "${scriptPath}" ${args.join(" ")}`;
    try {
      const { stdout, stderr } = await execAsync(command, {
        cwd: vaultPath,
        maxBuffer: 10 * 1024 * 1024
        // 10MB buffer
      });
      if (stderr) {
        console.warn("Python stderr:", stderr);
      }
      return stdout;
    } catch (error) {
      console.error("Python execution failed:", error);
      throw error;
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
var InboxProcessorView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.proposals = [];
    this.mocSuggestions = [];
    this.currentIndex = 0;
    this.isAnalyzing = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_INBOX;
  }
  getDisplayText() {
    return "Entropy Inbox";
  }
  getIcon() {
    return "inbox";
  }
  async onOpen() {
    await this.render();
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("entropy-inbox-view");
    const header = container.createDiv({ cls: "entropy-header" });
    header.createEl("h4", { text: "\u{1F4E5} Entropy Inbox Processor" });
    const count = await this.plugin.getInboxCount();
    const countEl = container.createDiv({ cls: "entropy-inbox-count" });
    countEl.createEl("p", { text: `Unprocessed items: ${count}` });
    const analyzeBtn = container.createEl("button", {
      text: this.isAnalyzing ? "\u23F3 Analyzing..." : "\u{1F50D} Analyze Inbox",
      cls: "mod-cta"
    });
    analyzeBtn.disabled = this.isAnalyzing || count === 0;
    analyzeBtn.addEventListener("click", async () => {
      await this.analyze();
    });
    if (this.plugin.settings.aiEnabled) {
      const aiStatus = container.createDiv({ cls: "entropy-ai-status" });
      aiStatus.createEl("p", {
        text: `\u2728 AI Analysis: Enabled (${this.plugin.settings.aiProvider})`,
        cls: "entropy-ai-enabled"
      });
      const estimatedCost = (count * 3e-3).toFixed(2);
      aiStatus.createEl("p", {
        text: `Estimated cost: ~$${estimatedCost}`,
        cls: "entropy-cost-estimate"
      });
    } else {
      const aiStatus = container.createDiv({ cls: "entropy-ai-status" });
      aiStatus.createEl("p", {
        text: "\u26A1 Fast mode (keyword matching)",
        cls: "entropy-ai-disabled"
      });
    }
    container.createEl("hr");
    if (this.mocSuggestions.length > 0 || this.proposals.length > 0) {
      await this.renderProposals(container);
    } else {
      container.createDiv({ cls: "entropy-empty" }).createEl("p", {
        text: count === 0 ? "\u2705 Inbox is empty!" : 'Click "Analyze Inbox" to start processing'
      });
    }
  }
  async analyze() {
    this.isAnalyzing = true;
    await this.render();
    try {
      const vaultPath = this.app.vault.adapter.basePath;
      const args = [`"${vaultPath}"`];
      if (this.plugin.settings.aiEnabled && this.plugin.settings.apiKey) {
        args.push("--use-ai");
        args.push("--provider", this.plugin.settings.aiProvider);
        args.push("--api-key", `"${this.plugin.settings.apiKey}"`);
        if (this.plugin.settings.model) {
          args.push("--model", this.plugin.settings.model);
        }
      }
      new import_obsidian.Notice("Analyzing inbox...");
      await this.plugin.runPythonScript("analyzer.py", args);
      await this.loadProposals();
      new import_obsidian.Notice(`\u2705 Found ${this.proposals.length} items to process`);
    } catch (error) {
      new import_obsidian.Notice("\u274C Analysis failed: " + error.message);
      console.error("Analysis error:", error);
    } finally {
      this.isAnalyzing = false;
      await this.render();
    }
  }
  async loadProposals() {
    const proposalsFile = this.app.vault.getAbstractFileByPath("proposals.md");
    if (!(proposalsFile instanceof import_obsidian.TFile)) {
      return;
    }
    const content = await this.app.vault.read(proposalsFile);
    this.parseProposals(content);
  }
  parseProposals(content) {
    var _a;
    this.proposals = [];
    this.mocSuggestions = [];
    const mocSection = content.match(/## 🎯 Suggested New MOCs\n([\s\S]+?)(?=\n## 📋|$)/);
    if (mocSection) {
      const mocText = mocSection[1];
      const mocBlocks = mocText.split(/### MOC Suggestion: /g).filter((b) => b.trim());
      for (const block of mocBlocks) {
        const nameMatch = block.match(/^(.+)/);
        const topicMatch = block.match(/\*\*Detected topic:\*\* (.+)/);
        const countMatch = block.match(/\*\*Items in cluster:\*\* (\d+)/);
        const itemsMatch = block.match(/\*\*Items:\*\*\n([\s\S]+?)(?=\n### ACTION)/);
        if (nameMatch && topicMatch && countMatch) {
          const items = [];
          if (itemsMatch) {
            const itemLines = itemsMatch[1].split("\n");
            for (const line of itemLines) {
              if (line.trim().startsWith("- ") && !line.includes("...")) {
                items.push(line.trim().substring(2));
              }
            }
          }
          this.mocSuggestions.push({
            name: nameMatch[1].trim(),
            topic: topicMatch[1],
            itemCount: parseInt(countMatch[1]),
            items,
            status: "pending"
          });
        }
      }
    }
    const itemBlocks = content.split(/## Item \d+: /g).filter((b) => b.trim());
    for (const block of itemBlocks) {
      const lines = block.split("\n");
      const filename = (_a = lines[0]) == null ? void 0 : _a.trim();
      if (!filename)
        continue;
      const wordCountMatch = block.match(/\*\*Word Count:\*\* (\d+)/);
      const pathMatch = block.match(/\*\*Path:\*\* `([^`]+)`/);
      const relationships = [];
      const relSection = block.match(/\*\*Relationships:\*\*\n\n([\s\S]+?)(?=\n\*\*Proposed Actions|$)/);
      if (relSection) {
        const relLines = relSection[1].split("\n");
        for (const line of relLines) {
          const relMatch = line.match(/- (.+) \((\d+)% confidence\)/);
          if (relMatch) {
            relationships.push({
              target: relMatch[1],
              confidence: parseInt(relMatch[2]),
              reason: ""
            });
          }
        }
      }
      const actions = [];
      const actionBlocks = block.split(/### ACTION \d+: /g).filter((b) => b.trim());
      for (const actionBlock of actionBlocks) {
        const typeMatch = actionBlock.match(/^(\w+)/);
        const targetMatch = actionBlock.match(/\*\*Target:\*\* `([^`]+)`/);
        const sectionMatch = actionBlock.match(/\*\*Section:\*\* (.+)/);
        const rationaleMatch = actionBlock.match(/\*\*Rationale:\*\* (.+)/);
        const contentMatch = actionBlock.match(/```diff\n(.+?)\n```/s);
        if (typeMatch && targetMatch && rationaleMatch) {
          actions.push({
            type: typeMatch[1].toLowerCase(),
            target: targetMatch[1],
            section: sectionMatch == null ? void 0 : sectionMatch[1],
            content: (contentMatch == null ? void 0 : contentMatch[1]) || "",
            rationale: rationaleMatch[1],
            status: "pending"
          });
        }
      }
      this.proposals.push({
        filename,
        wordCount: wordCountMatch ? parseInt(wordCountMatch[1]) : 0,
        path: (pathMatch == null ? void 0 : pathMatch[1]) || "",
        relationships,
        actions
      });
    }
  }
  async renderProposals(container) {
    if (this.mocSuggestions.length > 0) {
      const mocSection = container.createDiv({ cls: "entropy-moc-suggestions" });
      mocSection.createEl("h5", { text: "\u{1F3AF} Suggested New MOCs" });
      for (let i = 0; i < this.mocSuggestions.length; i++) {
        const moc = this.mocSuggestions[i];
        const mocCard = mocSection.createDiv({ cls: "entropy-moc-card" });
        mocCard.createEl("h6", { text: `MOC: ${moc.name}` });
        mocCard.createEl("p", { text: `Topic: ${moc.topic} \u2022 ${moc.itemCount} items` });
        const itemsList = mocCard.createEl("ul", { cls: "entropy-moc-items" });
        for (const item of moc.items.slice(0, 3)) {
          itemsList.createEl("li", { text: item });
        }
        if (moc.items.length > 3) {
          itemsList.createEl("li", { text: `... and ${moc.items.length - 3} more` });
        }
        const btnContainer = mocCard.createDiv({ cls: "entropy-action-buttons" });
        const acceptBtn = btnContainer.createEl("button", {
          text: "\u2713 Accept",
          cls: moc.status === "accept" ? "active" : ""
        });
        acceptBtn.addEventListener("click", () => {
          this.mocSuggestions[i].status = "accept";
          this.render();
        });
        const rejectBtn = btnContainer.createEl("button", {
          text: "\u2717 Reject",
          cls: moc.status === "reject" ? "active" : ""
        });
        rejectBtn.addEventListener("click", () => {
          this.mocSuggestions[i].status = "reject";
          this.render();
        });
      }
      container.createEl("hr");
    }
    if (this.proposals.length > 0) {
      const itemSection = container.createDiv({ cls: "entropy-item-proposals" });
      itemSection.createEl("h5", { text: `\u{1F4CB} Items (${this.currentIndex + 1}/${this.proposals.length})` });
      const proposal = this.proposals[this.currentIndex];
      const itemCard = itemSection.createDiv({ cls: "entropy-item-card" });
      itemCard.createEl("h6", { text: proposal.filename });
      itemCard.createEl("p", {
        text: `${proposal.wordCount} words`,
        cls: "entropy-meta"
      });
      if (proposal.relationships.length > 0) {
        const relSection = itemCard.createDiv({ cls: "entropy-relationships" });
        relSection.createEl("strong", { text: "Relates to:" });
        const relList = relSection.createEl("ul");
        for (const rel of proposal.relationships) {
          relList.createEl("li", { text: `${rel.target} (${rel.confidence}%)` });
        }
      }
      if (proposal.actions.length > 0) {
        const actionsSection = itemCard.createDiv({ cls: "entropy-actions" });
        actionsSection.createEl("strong", { text: "Proposed Actions:" });
        for (let i = 0; i < proposal.actions.length; i++) {
          const action = proposal.actions[i];
          const actionCard = actionsSection.createDiv({ cls: "entropy-action-card" });
          actionCard.createEl("p", { text: `${action.type.toUpperCase()}: ${action.target}` });
          if (action.section) {
            actionCard.createEl("p", { text: `Section: ${action.section}`, cls: "entropy-meta" });
          }
          actionCard.createEl("p", { text: action.rationale, cls: "entropy-rationale" });
          const btnContainer = actionCard.createDiv({ cls: "entropy-action-buttons" });
          const acceptBtn = btnContainer.createEl("button", {
            text: "\u2713 Accept",
            cls: action.status === "accept" ? "active" : ""
          });
          acceptBtn.addEventListener("click", () => {
            this.proposals[this.currentIndex].actions[i].status = "accept";
            this.render();
          });
          const rejectBtn = btnContainer.createEl("button", {
            text: "\u2717 Reject",
            cls: action.status === "reject" ? "active" : ""
          });
          rejectBtn.addEventListener("click", () => {
            this.proposals[this.currentIndex].actions[i].status = "reject";
            this.render();
          });
        }
      }
      const navSection = container.createDiv({ cls: "entropy-navigation" });
      if (this.currentIndex > 0) {
        const prevBtn = navSection.createEl("button", { text: "\u2190 Previous" });
        prevBtn.addEventListener("click", () => {
          this.currentIndex--;
          this.render();
        });
      }
      if (this.currentIndex < this.proposals.length - 1) {
        const nextBtn = navSection.createEl("button", { text: "Next \u2192" });
        nextBtn.addEventListener("click", () => {
          this.currentIndex++;
          this.render();
        });
      }
      const applyBtn = navSection.createEl("button", {
        text: "Apply All Changes",
        cls: "mod-cta"
      });
      applyBtn.addEventListener("click", async () => {
        await this.applyChanges();
      });
    }
  }
  async applyChanges() {
    try {
      const proposalsFile = this.app.vault.getAbstractFileByPath("proposals.md");
      if (!(proposalsFile instanceof import_obsidian.TFile)) {
        new import_obsidian.Notice("proposals.md not found");
        return;
      }
      let content = await this.app.vault.read(proposalsFile);
      for (const moc of this.mocSuggestions) {
        const pattern = new RegExp(
          `(### MOC Suggestion: ${moc.name}[\\s\\S]+?\\[)ACCEPT(\\] \\[)REJECT(\\])`,
          "g"
        );
        if (moc.status === "accept") {
          content = content.replace(pattern, "$1ACCEPT$2REJECT$3");
        } else if (moc.status === "reject") {
          content = content.replace(pattern, "$1ACCEPT$2REJECT$3");
        }
      }
      content = content.replace(/\[ACCEPT\]/g, "[REJECT]");
      for (const proposal of this.proposals) {
        for (const action of proposal.actions) {
          if (action.status === "accept") {
          }
        }
      }
      await this.app.vault.modify(proposalsFile, content);
      new import_obsidian.Notice("Applying changes...");
      const vaultPath = this.app.vault.adapter.basePath;
      await this.plugin.runPythonScript("apply.py", [`"${vaultPath}"`]);
      new import_obsidian.Notice("\u2705 Changes applied!");
      this.proposals = [];
      this.mocSuggestions = [];
      this.currentIndex = 0;
      await this.plugin.updateStatusBar();
      await this.render();
    } catch (error) {
      new import_obsidian.Notice("\u274C Failed to apply changes: " + error.message);
      console.error("Apply error:", error);
    }
  }
};
var EntropySettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Entropy Inbox Processor Settings" });
    new import_obsidian.Setting(containerEl).setName("Enable AI Analysis").setDesc("Use Claude or GPT for semantic understanding (requires API key)").addToggle((toggle) => toggle.setValue(this.plugin.settings.aiEnabled).onChange(async (value) => {
      this.plugin.settings.aiEnabled = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    if (this.plugin.settings.aiEnabled) {
      new import_obsidian.Setting(containerEl).setName("AI Provider").setDesc("Choose between Anthropic Claude or OpenAI GPT").addDropdown((dropdown) => dropdown.addOption("anthropic", "Anthropic (Claude)").addOption("openai", "OpenAI (GPT)").setValue(this.plugin.settings.aiProvider).onChange(async (value) => {
        this.plugin.settings.aiProvider = value;
        await this.plugin.saveSettings();
      }));
      new import_obsidian.Setting(containerEl).setName("API Key").setDesc("Your Anthropic or OpenAI API key (stored locally)").addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })).addButton((button) => button.setButtonText("Test Connection").onClick(async () => {
        await this.testConnection();
      }));
      new import_obsidian.Setting(containerEl).setName("Model (optional)").setDesc("Override default model (e.g., gpt-4o-mini for cheaper OpenAI)").addText((text) => text.setPlaceholder("Leave empty for default").setValue(this.plugin.settings.model).onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
      }));
      const securityEl = containerEl.createDiv({ cls: "entropy-security-notice" });
      securityEl.createEl("p", {
        text: "\u26A0\uFE0F Security Notice:",
        cls: "entropy-warning-title"
      });
      securityEl.createEl("p", {
        text: "API keys are stored in .obsidian/plugins/entropy-inbox-processor/data.json. Keep this folder out of git repositories!"
      });
      securityEl.createEl("p", {
        text: "Estimated cost: ~$0.15 for 50 items with Claude, ~$0.03 with GPT-4o-mini"
      });
    }
    new import_obsidian.Setting(containerEl).setName("Python Path").setDesc("Path to Python 3 executable").addText((text) => text.setPlaceholder("python3").setValue(this.plugin.settings.pythonPath).onChange(async (value) => {
      this.plugin.settings.pythonPath = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Behavior" });
    new import_obsidian.Setting(containerEl).setName("Auto-archive processed items").setDesc("Automatically move processed items to raw/processed/").addToggle((toggle) => toggle.setValue(this.plugin.settings.autoArchive).onChange(async (value) => {
      this.plugin.settings.autoArchive = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Confirm before applying").setDesc("Show confirmation dialog before applying changes").addToggle((toggle) => toggle.setValue(this.plugin.settings.confirmBeforeApply).onChange(async (value) => {
      this.plugin.settings.confirmBeforeApply = value;
      await this.plugin.saveSettings();
    }));
  }
  async testConnection() {
    try {
      new import_obsidian.Notice("Testing connection...");
      const result = await this.plugin.runPythonScript("llm_analyzer.py", [
        this.plugin.settings.aiProvider,
        `"${this.plugin.settings.apiKey}"`
      ]);
      if (result.includes("\u2705")) {
        new import_obsidian.Notice("\u2705 Connection successful!");
      } else {
        new import_obsidian.Notice("\u274C Connection failed");
      }
    } catch (error) {
      new import_obsidian.Notice("\u274C Connection failed: " + error.message);
    }
  }
};
